import type { Metadata } from "next";
import { cookies } from "next/headers";
import Navbar from "../components/Navbar";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
const albertSans = Albert_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  const name = cookieStore.get("name")?.value;

  const userData = {
    token: token,
    name: name,
  };

  return (
    <html lang="en">
      <body className={albertSans.className}>
        <Navbar userData={userData} />
        {children}
      </body>
    </html>
  );
}
